# Generated by Django 4.1.7 on 2023-02-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('date', models.DateTimeField()),
                ('readCount', models.IntegerField()),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
