# Generated by Django 4.1.7 on 2023-06-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOSFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('files', models.FileField(upload_to='ios_files/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='title',
            old_name='body',
            new_name='body_kazak',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='body_ar',
            new_name='body_krgyz',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='body_kz',
            new_name='body_tajik',
        ),
        migrations.RemoveField(
            model_name='title',
            name='body_turk',
        ),
    ]
