# Generated by Django 4.1.7 on 2024-06-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_iosfiles_rename_body_title_body_kazak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='readCount',
            field=models.IntegerField(blank=True),
        ),
    ]
