# Generated by Django 5.0.6 on 2024-06-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0003_alter_title_readcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='body_eng',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='title',
            name='body_kazak',
        ),
        migrations.RemoveField(
            model_name='title',
            name='body_krgyz',
        ),
        migrations.RemoveField(
            model_name='title',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='title',
            name='body_tajik',
        ),
        migrations.RemoveField(
            model_name='title',
            name='body_uz',
        ),
    ]
