# Generated by Django 5.0.6 on 2024-06-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0004_rename_body_eng_title_body_remove_title_body_kazak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='body_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='body_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='body_tj',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='title_kk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='title_kz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='title_tj',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
