# Generated by Django 5.0.6 on 2024-06-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0005_title_body_en_title_body_kk_title_body_kz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='readCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
